/**
 * SiteSubjectFormPage — full-page Create / Edit Subject for site personnel.
 *
 * Routes:
 *   /site/capture/subjects/new
 *   /site/capture/subjects/:subjectId/edit
 *
 * Mirrors the sponsor-side form-page layout (PersonnelFormPage / SiteFormPage).
 * Fields:
 *   Subject Name        (text, required)
 *   Subject Initials    (text, optional)
 *   Enrollment Date     (date)
 *   Enrollment Status   (Screening | Enrolled | Completed | Withdrawn | Discontinued)
 *
 * Subject ID (subject_number, e.g. S001) is generated by the backend on
 * create and shown as a read-only field in edit mode.
 */

import { useEffect, useState, useCallback } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { ArrowLeft, Loader2 } from 'lucide-react';

import FormField from '@/components/form/FormField';
import { siteWorkspaceClient } from '@/features/site/api/siteWorkspaceClient';
import { addToast } from '@/app/notificationSlice';

import styles from '@/features/sponsor/pages/PersonnelFormPage.module.css';

const ENROLLMENT_STATUSES = [
  { value: 'Screening',    label: 'Screening' },
  { value: 'Enrolled',     label: 'Enrolled' },
  { value: 'Completed',    label: 'Completed' },
  { value: 'Withdrawn',    label: 'Withdrawn' },
  { value: 'Discontinued', label: 'Discontinued' },
];

const EMPTY = {
  subjectNumber:    '',  // populated by backend on create; shown read-only after
  subjectName:      '',
  subjectInitials:  '',
  enrollmentDate:   '',
  enrollmentStatus: 'Screening',
};

function ic(s, err) { return err ? `${s.input} ${s.inputError}` : s.input; }

function validate(form) {
  const e = {};
  if (!form.subjectName.trim()) e.subjectName = 'Subject Name is required.';
  if (form.subjectInitials && form.subjectInitials.length > 10) {
    e.subjectInitials = 'Initials must be 10 characters or fewer.';
  }
  return e;
}

// Normalise an API row (possibly snake_case) into our form state.
function fromRow(row) {
  const r = row?.subject ?? row?.item ?? row ?? {};
  return {
    subjectNumber:    r.subject_number    ?? r.subjectNumber    ?? '',
    subjectName:      r.subject_name      ?? r.subjectName      ?? '',
    subjectInitials:  r.subject_initials  ?? r.subjectInitials  ?? '',
    enrollmentDate:   (r.enrolled_at      ?? r.enrolledAt       ?? '').slice(0, 10),
    enrollmentStatus: r.enrollment_status ?? r.enrollmentStatus ?? 'Screening',
  };
}

export default function SiteSubjectFormPage() {
  const { subjectId } = useParams();
  const navigate      = useNavigate();
  const dispatch      = useDispatch();
  const isEdit        = !!subjectId;

  const [form,     setForm]     = useState(EMPTY);
  const [errors,   setErrors]   = useState({});
  const [loading,  setLoading]  = useState(isEdit);
  const [saving,   setSaving]   = useState(false);
  const [apiError, setApiError] = useState('');

  // Load existing subject in edit mode.
  useEffect(() => {
    if (!isEdit) return;
    let cancelled = false;
    setLoading(true);
    siteWorkspaceClient.getSubject(subjectId)
      .then((res) => { if (!cancelled) setForm(fromRow(res)); })
      .catch(() => {
        if (!cancelled) {
          dispatch(addToast({ type: 'error', message: 'Failed to load subject record.' }));
        }
      })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [isEdit, subjectId, dispatch]);

  const setField = (key) => (e) => {
    const value = e.target.value;
    setForm((f) => ({ ...f, [key]: value }));
    if (errors[key]) setErrors((er) => ({ ...er, [key]: undefined }));
  };

  const handleSubmit = useCallback(async (e) => {
    e?.preventDefault?.();
    const next = validate(form);
    setErrors(next);
    if (Object.keys(next).length > 0) return;

    setSaving(true);
    setApiError('');
    try {
      const payload = {
        subject_name:      form.subjectName.trim(),
        subject_initials:  form.subjectInitials.trim() || null,
        enrollment_date:   form.enrollmentDate || null,
        enrollment_status: form.enrollmentStatus,
      };
      if (isEdit) {
        await siteWorkspaceClient.updateSubject(subjectId, payload);
        dispatch(addToast({ type: 'success', message: 'Subject updated.' }));
      } else {
        await siteWorkspaceClient.createSubject(payload);
        dispatch(addToast({ type: 'success', message: 'Subject enrolled.' }));
      }
      navigate('/site/capture');
    } catch (err) {
      setApiError(err?.message ?? 'Save failed. Please try again.');
    } finally {
      setSaving(false);
    }
  }, [form, isEdit, subjectId, dispatch, navigate]);

  if (loading) {
    return (
      <div className={styles.loadingWrap}>
        <Loader2 size={28} className={styles.spinner} />
        <p>Loading subject…</p>
      </div>
    );
  }

  return (
    <form className={styles.page} onSubmit={handleSubmit} noValidate>
      <Link to="/site/capture" className={styles.backLink}>
        <ArrowLeft size={14} /> Back to Data Capture
      </Link>

      <div>
        <h1 className={styles.title}>{isEdit ? 'Edit Subject' : 'Enroll Subject'}</h1>
        <p className={styles.sub}>
          {isEdit
            ? 'Update the subject record. The Subject ID is fixed once created.'
            : 'The Subject ID is generated automatically when you save.'}
        </p>
      </div>

      {apiError && <div className={styles.apiError}>{apiError}</div>}

      <div className={styles.card}>
        <div className={styles.row2}>
          <FormField
            label="Subject ID"
            name="subjectNumber"
            helpText={isEdit ? '' : 'Auto-generated on save (e.g. S001).'}
          >
            <input
              id="subjectNumber"
              type="text"
              className={styles.input}
              value={form.subjectNumber || (isEdit ? '' : 'Auto-generated')}
              readOnly
              disabled
            />
          </FormField>

          <FormField label="Subject Name" name="subjectName" required error={errors.subjectName}>
            <input
              id="subjectName"
              type="text"
              className={ic(styles, errors.subjectName)}
              value={form.subjectName}
              onChange={setField('subjectName')}
              placeholder="e.g. Anonymised subject identifier"
              autoFocus
            />
          </FormField>
        </div>

        <div className={styles.row2}>
          <FormField
            label="Subject Initials"
            name="subjectInitials"
            error={errors.subjectInitials}
            helpText="Up to 10 characters."
          >
            <input
              id="subjectInitials"
              type="text"
              className={ic(styles, errors.subjectInitials)}
              value={form.subjectInitials}
              onChange={setField('subjectInitials')}
              maxLength={10}
              placeholder="e.g. JD"
            />
          </FormField>

          <FormField label="Enrollment Date" name="enrollmentDate">
            <input
              id="enrollmentDate"
              type="date"
              className={styles.input}
              value={form.enrollmentDate}
              onChange={setField('enrollmentDate')}
            />
          </FormField>
        </div>

        <FormField label="Enrollment Status" name="enrollmentStatus">
          <select
            id="enrollmentStatus"
            className={styles.input}
            value={form.enrollmentStatus}
            onChange={setField('enrollmentStatus')}
          >
            {ENROLLMENT_STATUSES.map((o) => (
              <option key={o.value} value={o.value}>{o.label}</option>
            ))}
          </select>
        </FormField>
      </div>

      <div className={styles.footer}>
        <button
          type="button"
          className={styles.btnCancel}
          onClick={() => navigate('/site/capture')}
          disabled={saving}
        >
          Cancel
        </button>
        <button type="submit" className={styles.btnSave} disabled={saving}>
          {saving ? 'Saving…' : isEdit ? 'Save Changes' : 'Create Subject'}
        </button>
      </div>
    </form>
  );
}
