/**
 * SiteSubjectFormPage — full-page Create / Edit Subject for site personnel.
 *
 * Routes:
 *   /site/capture/subjects/new
 *   /site/capture/subjects/:subjectId/edit
 *
 * Mirrors the sponsor-side form-page layout (PersonnelFormPage / SiteFormPage).
 * Fields:
 *   Subject Initials    (text, optional)
 *   Enrollment Date     (date)
 *   Enrollment Status   (Pending | Enrolled | Completed | Withdrawn)
 *
 * Subject ID (subject_number, e.g. SUB-SUN001-001) is generated by the backend
 * on create and shown as a read-only field. New subjects default to Enrolled.
 */

import { useEffect, useState, useCallback } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { ArrowLeft, Loader2 } from 'lucide-react';

import FormField from '@/components/form/FormField';
import PlatformDatePicker from '@/components/form/PlatformDatePicker';
import { siteWorkspaceClient } from '@/features/site/api/siteWorkspaceClient';
import { addToast } from '@/app/notificationSlice';
import { toIsoDate } from '@/utils/formatDate';

// Enrollment Date window: today is the latest allowed date (no future dates),
// and the picker reaches back at most 30 days.
const todayIso     = () => toIsoDate(new Date());
const thirtyAgoIso = () => {
  const d = new Date();
  d.setDate(d.getDate() - 30);
  return toIsoDate(d);
};

import styles from '@/features/sponsor/pages/PersonnelFormPage.module.css';

const ENROLLMENT_STATUSES = [
  { value: 'Pending',      label: 'Pending' },
  { value: 'Enrolled',     label: 'Enrolled' },
  { value: 'Completed',    label: 'Completed' },
  { value: 'Withdrawn',    label: 'Withdrawn' },
  { value: 'Discontinued', label: 'Discontinued' },
];

const EMPTY = {
  subjectNumber:    '',  // populated by backend on create; shown read-only after
  subjectInitials:  '',
  enrollmentDate:   '',
  enrollmentStatus: 'Enrolled',  // new subjects start Enrolled; → Pending on data capture
};

function ic(s, err) { return err ? `${s.input} ${s.inputError}` : s.input; }

// Subject initials: exactly 3 characters, capital letters only, dashes allowed
// (e.g. ABC, A-B, --C).
const INITIALS_RE = /^[A-Z-]{3}$/;
// Strip anything that isn't a letter or dash, force uppercase, cap at 3 chars.
const sanitizeInitials = (raw) =>
  (raw ?? '').toUpperCase().replace(/[^A-Z-]/g, '').slice(0, 3);

function validate(form) {
  const e = {};
  if (form.subjectInitials && !INITIALS_RE.test(form.subjectInitials)) {
    e.subjectInitials = 'Initials must be exactly 3 characters — capital letters or dashes (e.g. ABC, A-B, --C).';
  }
  if (form.enrollmentDate) {
    const picked = form.enrollmentDate.slice(0, 10);
    if (picked > todayIso()) {
      e.enrollmentDate = 'Enrollment Date cannot be in the future.';
    } else if (picked < thirtyAgoIso()) {
      e.enrollmentDate = 'Enrollment Date cannot be more than 30 days ago.';
    }
  }
  return e;
}

// Normalise an API row (possibly snake_case) into our form state.
function fromRow(row) {
  const r = row?.subject ?? row?.item ?? row ?? {};
  return {
    subjectNumber:    r.subject_number    ?? r.subjectNumber    ?? '',
    subjectInitials:  r.subject_initials  ?? r.subjectInitials  ?? '',
    enrollmentDate:   (r.enrolled_at      ?? r.enrolledAt       ?? '').slice(0, 10),
    enrollmentStatus: r.enrollment_status ?? r.enrollmentStatus ?? 'Enrolled',
  };
}

export default function SiteSubjectFormPage() {
  const { subjectId } = useParams();
  const navigate      = useNavigate();
  const dispatch      = useDispatch();
  const isEdit        = !!subjectId;

  // On create, default the Enrollment Date to today; edit mode overwrites it
  // from the loaded record.
  const [form,     setForm]     = useState(() =>
    isEdit ? EMPTY : { ...EMPTY, enrollmentDate: todayIso() });
  const [errors,   setErrors]   = useState({});
  const [loading,  setLoading]  = useState(isEdit);
  const [saving,   setSaving]   = useState(false);
  const [apiError, setApiError] = useState('');

  // Load existing subject in edit mode.
  useEffect(() => {
    if (!isEdit) return;
    let cancelled = false;
    setLoading(true);
    siteWorkspaceClient.getSubject(subjectId)
      .then((res) => { if (!cancelled) setForm(fromRow(res)); })
      .catch(() => {
        if (!cancelled) {
          dispatch(addToast({ type: 'error', message: 'Failed to load subject record.' }));
        }
      })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [isEdit, subjectId, dispatch]);

  const setField = (key) => (e) => {
    const value = e.target.value;
    setForm((f) => ({ ...f, [key]: value }));
    if (errors[key]) setErrors((er) => ({ ...er, [key]: undefined }));
  };

  const handleSubmit = useCallback(async (e) => {
    e?.preventDefault?.();
    const next = validate(form);
    setErrors(next);
    if (Object.keys(next).length > 0) return;

    setSaving(true);
    setApiError('');
    try {
      const payload = {
        subject_initials:  form.subjectInitials.trim() || null,
        enrollment_date:   form.enrollmentDate || null,
        enrollment_status: form.enrollmentStatus,
      };
      if (isEdit) {
        await siteWorkspaceClient.updateSubject(subjectId, payload);
        dispatch(addToast({ type: 'success', message: 'Subject updated.' }));
      } else {
        await siteWorkspaceClient.createSubject(payload);
        dispatch(addToast({ type: 'success', message: 'Subject enrolled.' }));
      }
      navigate('/site/capture');
    } catch (err) {
      setApiError(err?.message ?? 'Save failed. Please try again.');
    } finally {
      setSaving(false);
    }
  }, [form, isEdit, subjectId, dispatch, navigate]);

  if (loading) {
    return (
      <div className={styles.loadingWrap}>
        <Loader2 size={28} className={styles.spinner} />
        <p>Loading subject…</p>
      </div>
    );
  }

  return (
    <form className={styles.page} onSubmit={handleSubmit} noValidate>
      <Link to="/site/capture" className={styles.backLink}>
        <ArrowLeft size={14} /> Back to Data Capture
      </Link>

      <div>
        <h1 className={styles.title}>{isEdit ? 'Edit Subject' : 'Enroll Subject'}</h1>
        <p className={styles.sub}>
          {isEdit
            ? 'Update the subject record. The Subject ID is fixed once created.'
            : 'The Subject ID is generated automatically when you save.'}
        </p>
      </div>

      {apiError && <div className={styles.apiError}>{apiError}</div>}

      <div className={styles.card}>
        <div className={styles.row2}>
          <FormField label="Subject ID" name="subjectNumber">
            <input
              id="subjectNumber"
              type="text"
              className={styles.input}
              value={form.subjectNumber || (isEdit ? '' : 'Auto-generated')}
              readOnly
              disabled
            />
          </FormField>

          <FormField
            label="Subject Initials"
            name="subjectInitials"
            error={errors.subjectInitials}
            helpText="Exactly 3 characters — capital letters or dashes (e.g. ABC, A-B, --C)."
          >
            <input
              id="subjectInitials"
              type="text"
              className={ic(styles, errors.subjectInitials)}
              value={form.subjectInitials}
              onChange={(e) => {
                const value = sanitizeInitials(e.target.value);
                setForm((f) => ({ ...f, subjectInitials: value }));
                if (errors.subjectInitials) {
                  setErrors((er) => ({ ...er, subjectInitials: undefined }));
                }
              }}
              maxLength={3}
              placeholder="ABC"
              style={{ textTransform: 'uppercase' }}
              autoFocus
            />
          </FormField>
        </div>

        <div className={styles.row2}>
          <FormField
            label="Enrollment Date"
            name="enrollmentDate"
            error={errors.enrollmentDate}
            helpText="Today or within the last 30 days — future dates are not allowed."
          >
            <PlatformDatePicker
              id="enrollmentDate"
              className={styles.input}
              value={form.enrollmentDate}
              onChange={(v) => {
                // PlatformDatePicker emits a bare ISO string (not an event).
                const value = typeof v === 'string' ? v : (v?.target?.value ?? '');
                setForm((f) => ({ ...f, enrollmentDate: value }));
                if (errors.enrollmentDate) {
                  setErrors((er) => ({ ...er, enrollmentDate: undefined }));
                }
              }}
              min={thirtyAgoIso()}
              max={todayIso()}
              error={!!errors.enrollmentDate}
            />
          </FormField>

          {/* Status is set automatically on create (new subjects start
              "Enrolled", then move to "Pending" when data capture begins).
              It only becomes editable here once the subject exists. */}
          {isEdit && (
            <FormField label="Enrollment Status" name="enrollmentStatus">
              <select
                id="enrollmentStatus"
                className={styles.input}
                value={form.enrollmentStatus}
                onChange={setField('enrollmentStatus')}
              >
                {ENROLLMENT_STATUSES.map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
            </FormField>
          )}
        </div>
      </div>

      <div className={styles.footer}>
        <button
          type="button"
          className={styles.btnCancel}
          onClick={() => navigate('/site/capture')}
          disabled={saving}
        >
          Cancel
        </button>
        <button type="submit" className={styles.btnSave} disabled={saving}>
          {saving ? 'Saving…' : isEdit ? 'Save Changes' : 'Create Subject'}
        </button>
      </div>
    </form>
  );
}
